//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDato.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_comments
    {
        public decimal comment_ID { get; set; }
        public decimal comment_post_ID { get; set; }
        public string comment_author { get; set; }
        public string comment_author_email { get; set; }
        public string comment_author_url { get; set; }
        public string comment_author_IP { get; set; }
        public System.DateTime comment_date { get; set; }
        public System.DateTime comment_date_gmt { get; set; }
        public string comment_content { get; set; }
        public int comment_karma { get; set; }
        public string comment_approved { get; set; }
        public string comment_agent { get; set; }
        public string comment_type { get; set; }
        public decimal comment_parent { get; set; }
        public decimal user_id { get; set; }
    }
}
