//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDato.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_links
    {
        public decimal link_id { get; set; }
        public string link_url { get; set; }
        public string link_name { get; set; }
        public string link_image { get; set; }
        public string link_target { get; set; }
        public string link_description { get; set; }
        public string link_visible { get; set; }
        public decimal link_owner { get; set; }
        public int link_rating { get; set; }
        public System.DateTime link_updated { get; set; }
        public string link_rel { get; set; }
        public string link_notes { get; set; }
        public string link_rss { get; set; }
    }
}
