//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDato.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_novedad
    {
        public long wp_nov_id { get; set; }
        public string wp_nov_posts_id { get; set; }
        public long wp_tpo_nov { get; set; }
        public string wp_nov_val_ant { get; set; }
        public string wp_nov_val_act { get; set; }
        public System.DateTime wp_nov_fecha { get; set; }
        public Nullable<bool> wp_nov_activa { get; set; }
        public string filtro { get; set; }
        public string wp_nov_dia_ing { get; set; }
        public string wp_nov_semana_ing { get; set; }
    }
}
