//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDato.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_tpo_novedad
    {
        public long wp_tpo_nov_id { get; set; }
        public string wp_tpo_nov_desc { get; set; }
        public string wp_tpo_nov_status { get; set; }
    }
}
