//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDato.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_term_taxonomy
    {
        public decimal term_taxonomy_id { get; set; }
        public decimal term_id { get; set; }
        public string taxonomy { get; set; }
        public string description { get; set; }
        public decimal parent { get; set; }
        public long count { get; set; }
    }
}
