//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDato.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_users_valid
    {
        public int wp_usr_val_id { get; set; }
        public Nullable<long> id_user { get; set; }
        public string wp_usr_val_token { get; set; }
        public Nullable<System.DateTime> wp_usr_val_date { get; set; }
        public string wp_usr_val_status { get; set; }
    }
}
