//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDato.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_woocommerce_api_keys
    {
        public decimal key_id { get; set; }
        public decimal user_id { get; set; }
        public string description { get; set; }
        public string permissions { get; set; }
        public string consumer_key { get; set; }
        public string consumer_secret { get; set; }
        public string nonces { get; set; }
        public string truncated_key { get; set; }
        public Nullable<System.DateTime> last_access { get; set; }
    }
}
