//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDato.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_woocommerce_tax_rate_locations
    {
        public decimal location_id { get; set; }
        public string location_code { get; set; }
        public decimal tax_rate_id { get; set; }
        public string location_type { get; set; }
    }
}
