//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDato.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_woocommerce_payment_tokens
    {
        public decimal token_id { get; set; }
        public string gateway_id { get; set; }
        public string token { get; set; }
        public decimal user_id { get; set; }
        public string type { get; set; }
        public bool is_default { get; set; }
    }
}
