//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDato.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_woocommerce_attribute_taxonomies
    {
        public decimal attribute_id { get; set; }
        public string attribute_name { get; set; }
        public string attribute_label { get; set; }
        public string attribute_type { get; set; }
        public string attribute_orderby { get; set; }
        public int attribute_public { get; set; }
    }
}
