//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDato.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_woocommerce_shipping_zone_methods
    {
        public decimal zone_id { get; set; }
        public decimal instance_id { get; set; }
        public string method_id { get; set; }
        public decimal method_order { get; set; }
        public bool is_enabled { get; set; }
    }
}
