//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDato.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_woocommerce_log
    {
        public decimal log_id { get; set; }
        public System.DateTime timestamp { get; set; }
        public short level { get; set; }
        public string source { get; set; }
        public string message { get; set; }
        public string context { get; set; }
    }
}
