//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDato.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_woocommerce_tax_rates
    {
        public decimal tax_rate_id { get; set; }
        public string tax_rate_country { get; set; }
        public string tax_rate_state { get; set; }
        public string tax_rate { get; set; }
        public string tax_rate_name { get; set; }
        public decimal tax_rate_priority { get; set; }
        public int tax_rate_compound { get; set; }
        public int tax_rate_shipping { get; set; }
        public decimal tax_rate_order { get; set; }
        public string tax_rate_class { get; set; }
    }
}
