//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDato.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_woocommerce_downloadable_product_permissions
    {
        public decimal permission_id { get; set; }
        public string download_id { get; set; }
        public decimal product_id { get; set; }
        public decimal order_id { get; set; }
        public string order_key { get; set; }
        public string user_email { get; set; }
        public Nullable<decimal> user_id { get; set; }
        public string downloads_remaining { get; set; }
        public System.DateTime access_granted { get; set; }
        public Nullable<System.DateTime> access_expires { get; set; }
        public decimal download_count { get; set; }
    }
}
